/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenFactorySol from "./ERC20TokenFactory.sol";
export type { erc20TokenFactorySol };
export type { AddressBook } from "./AddressBook";
export type { DomainRegistry } from "./DomainRegistry";
export type { RedeemLinksEscrow } from "./RedeemLinksEscrow";
export type { SecureStorage } from "./SecureStorage";
export type { UniversalNFT } from "./UniversalNFT";
