/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomERC20Token } from "./CustomERC20Token";
export type { ERC20TokenFactory } from "./ERC20TokenFactory";
