/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomERC20Token__factory } from "./CustomERC20Token__factory";
export { ERC20TokenFactory__factory } from "./ERC20TokenFactory__factory";
